import { renderHook, act } from "@testing-library/react";
import { useTranslationSession } from "../useTranslationSession";
import { useTranslationQuery } from "../useTranslationQuery";

// Mocks
jest.mock("../useTranslationQuery");
jest.mock("../useSessionMachine", () => {
  const dispatch = jest.fn();
  return {
    useSessionMachine: () => ({
      state: { status: "practicing", batchIndex: 0 },
      dispatch,
    }),
  };
});
jest.mock("react-redux", () => {
  const dispatch = jest.fn();
  return {
    useDispatch: () => dispatch,
    useSelector: () => ({ shuffleSentences: false, redoErrors: false }),
  };
});

describe("useTranslationSession", () => {
  beforeEach(() => {
    (useTranslationQuery as jest.Mock).mockReturnValue({
      data: [
        { id: "1", sentence: "A", translation: "B", userInput: "" },
        { id: "2", sentence: "C", translation: "D", userInput: "" },
      ],
      isLoading: false,
      error: null,
    });
  });

  test("should initialize with rows from query", () => {
    const { result } = renderHook(() => useTranslationSession("A1", "Unit1"));

    // Check if local state populated (note: useEffect might need to run)
    // The hook initializes allRows via useEffect when queryRows changes
    expect(result.current.allRows).toHaveLength(2);
    expect(result.current.rows).toHaveLength(2); // Batch 0
  });

  test("should update row input", () => {
    const { result } = renderHook(() => useTranslationSession("A1", "Unit1"));

    act(() => {
      result.current.updateRowInput(0, "Tested");
    });

    expect(result.current.rows[0].userInput).toBe("Tested");
  });

  test("should update row status (correct/incorrect)", () => {
    const { result } = renderHook(() => useTranslationSession("A1", "Unit1"));

    // ID is generated by the hook (A1-Unit1-0), so we get it from the current state
    const targetId = result.current.rows[0].id;

    act(() => {
      result.current.updateRow(targetId, { isCorrect: true });
    });

    expect(result.current.rows[0].isCorrect).toBe(true);
  });
});
